# -*- coding: utf-8 -*-
"""Semantic_Segmemtation_Demo_Code.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19gw9zux__wPbNxDXhxBkwbxsztZmmLfS

# Tested Using Unseen Input Image
"""

# I mounted Google Drive to access my model and dataset
from google.colab import drive
drive.mount('/content/drive')

# I imported TensorFlow for loading and running the model
import tensorflow as tf

# I imported NumPy for numerical operations
import numpy as np

# I imported Matplotlib to visualize images and results
import matplotlib.pyplot as plt

# I imported OS to handle file paths
import os

# I imported OpenCV to help with image overlay operations
import cv2

# I imported image utilities for loading and converting images
from tensorflow.keras.preprocessing.image import load_img, img_to_array

# I loaded the trained water body segmentation model from my Google Drive
model = tf.keras.models.load_model(
    '/content/drive/MyDrive/Colab Notebooks/water_segmentation_model.h5',
    compile=False
)

# I confirmed that the model was loaded successfully
print("I successfully loaded the water body segmentation model.")

# I defined the dataset path where my satellite images are stored
base_path = "/content/drive/MyDrive/Colab Notebooks/Water Body/Water Bodies Dataset/Images"

# I selected one sample image from the dataset
img_path = os.path.join(base_path, os.listdir(base_path)[0])

# I loaded and resized the image to match model input size
img = load_img(img_path, target_size=(256,256))

# I converted the image into a NumPy array and normalized pixel values
img_array = img_to_array(img) / 255.0

# I printed basic image information for verification
print("I checked image shape:", img_array.shape)
print("I checked pixel value range:", np.min(img_array), "to", np.max(img_array))

# I displayed the input image
plt.imshow(img)
plt.title("Input Image")
plt.axis("off")
plt.show()

# I performed segmentation prediction using the model
pred = model.predict(np.expand_dims(img_array, axis=0))[0]

# I converted prediction into a binary mask using a threshold
pred_mask = (pred > 0.5).astype(np.float32).squeeze()

# I displayed the predicted mask
plt.imshow(pred_mask, cmap='gray')
plt.title("Predicted Water Mask")
plt.axis("off")
plt.show()

# I calculated the percentage of water area in the image
water_pixels = np.sum(pred_mask)
total_pixels = pred_mask.size
water_percentage = (water_pixels / total_pixels) * 100

# I printed the water coverage percentage
print("I calculated water area percentage:", round(water_percentage, 2), "%")

# I created an overlay image to highlight detected water regions
overlay = img_array.copy()

# I highlighted water pixels in red color
overlay[:,:,0] = overlay[:,:,0] * (1 - pred_mask) + pred_mask * 1.0

# I displayed the overlay image
plt.imshow(overlay)
plt.title("Water Region Highlighted")
plt.axis("off")
plt.show()

# I explained the result
print("The white regions in the mask represent detected water bodies.")
print("The highlighted regions show where water is present in the image.")

# I selected a new unseen image for testing
new_img_path = os.path.join(base_path, os.listdir(base_path)[5])

# I loaded and processed the unseen image
img = load_img(new_img_path, target_size=(256,256))
img_array = img_to_array(img) / 255.0

# I displayed the unseen input image
plt.imshow(img)
plt.title("New Input Image")
plt.axis("off")
plt.show()

# I predicted segmentation mask for the unseen image
pred = model.predict(np.expand_dims(img_array, axis=0))[0]

# I converted prediction into binary mask
pred_mask = (pred > 0.5).astype(np.float32).squeeze()

# I displayed the predicted mask for unseen image
plt.imshow(pred_mask, cmap='gray')
plt.title("Predicted Mask")
plt.axis("off")
plt.show()

# I calculated water percentage for unseen image
water_pixels = np.sum(pred_mask)
total_pixels = pred_mask.size
water_percentage = (water_pixels / total_pixels) * 100

# I printed the water percentage
print("I calculated water area percentage for unseen image:", round(water_percentage, 2), "%")

# I created overlay for unseen image
overlay = img_array.copy()
overlay[:,:,0] = overlay[:,:,0] * (1 - pred_mask) + pred_mask * 1.0

# I displayed highlighted water regions
plt.imshow(overlay)
plt.title("Water Body Highlighted")
plt.axis("off")
plt.show()

# I concluded the demonstration
print("I demonstrated water body detection using segmentation on both sample and unseen images.")
print("This demonstrates that the model can accurately detect and quantify water bodies in satellite images.")

"""# Random"""

# I mounted Google Drive to access my model and dataset
from google.colab import drive
drive.mount('/content/drive')

# I imported required libraries for model inference and visualization
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt
import os
import random
from tensorflow.keras.preprocessing.image import load_img, img_to_array

# I loaded the trained water body segmentation model
model = tf.keras.models.load_model(
    '/content/drive/MyDrive/Colab Notebooks/water_segmentation_model.h5',
    compile=False
)

# I confirmed that the model was loaded successfully
print("I successfully loaded the water body segmentation model.")

# I defined the dataset path containing satellite images
base_path = "/content/drive/MyDrive/Colab Notebooks/Water Body/Water Bodies Dataset/Images"

# I filtered valid image files from the dataset directory
files = [f for f in os.listdir(base_path) if f.endswith(('.jpg', '.png'))]

# I started the live demonstration
print("\nI started the live demonstration.")

# I selected a sample image from the dataset for initial testing
img_path = os.path.join(base_path, files[0])

# I loaded and resized the sample image
img = load_img(img_path, target_size=(256,256))

# I converted the image into a numerical array and normalized pixel values
img_array = img_to_array(img) / 255.0

# I displayed the sample input image
plt.imshow(img)
plt.title("Sample Input Image")
plt.axis("off")
plt.show()

# I performed segmentation prediction using the model
pred = model.predict(np.expand_dims(img_array, axis=0))[0]

# I converted the prediction into a binary mask
pred_mask = (pred > 0.5).astype(np.float32).squeeze()

# I displayed the predicted mask
plt.imshow(pred_mask, cmap='gray')
plt.title("Predicted Water Mask")
plt.axis("off")
plt.show()

# I created an overlay to highlight detected water regions
overlay = img_array.copy()
overlay[:,:,0] = overlay[:,:,0] * (1 - pred_mask) + pred_mask * 1.0

# I displayed the highlighted water regions
plt.imshow(overlay)
plt.title("Water Region Highlighted")
plt.axis("off")
plt.show()

# I calculated the percentage of water area in the image
water_percentage = (np.sum(pred_mask) / pred_mask.size) * 100

# I printed the water area percentage
print("Water area percentage:", round(water_percentage, 2), "%")

# I explained what the mask and overlay represent
print("The white regions represent detected water bodies.")
print("The highlighted regions show where water is present.")

# I tested the model on a new unseen image selected randomly
print("\nI now tested the model on a new unseen image.")

# I randomly selected a new image from the dataset
new_img_path = os.path.join(base_path, random.choice(files))

# I displayed the path of the selected image
print("Selected new image:", new_img_path)

# I loaded and processed the unseen image
img = load_img(new_img_path, target_size=(256,256))
img_array = img_to_array(img) / 255.0

# I displayed the unseen input image
plt.imshow(img)
plt.title("New Input Image")
plt.axis("off")
plt.show()

# I predicted the segmentation mask for the unseen image
pred = model.predict(np.expand_dims(img_array, axis=0))[0]

# I converted the prediction into a binary mask
pred_mask = (pred > 0.5).astype(np.float32).squeeze()

# I displayed the predicted mask
plt.imshow(pred_mask, cmap='gray')
plt.title("Predicted Mask")
plt.axis("off")
plt.show()

# I created an overlay to highlight detected water regions
overlay = img_array.copy()
overlay[:,:,0] = overlay[:,:,0] * (1 - pred_mask) + pred_mask * 1.0

# I displayed the highlighted water regions
plt.imshow(overlay)
plt.title("Water Body Highlighted")
plt.axis("off")
plt.show()

# I calculated the water percentage for the unseen image
water_percentage = (np.sum(pred_mask) / pred_mask.size) * 100

# I printed the calculated percentage
print("Water area percentage:", round(water_percentage, 2), "%")

# I explained that the model works on unseen data
print("This demonstrated that the model can detect water bodies on unseen data.")

# I concluded the demonstration
print("\nI successfully completed the live demonstration.")